#dev环境  mysql7.0
v2:
  fileurl: D:/upload
  filetemp: D:/upload/temp

# mongodb 日志级别
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO
spring:
  #  LOWER_CAMEL_CASE    userName    默认策略
  #  KEBAB_CASE    user-name
  #  LOWER_CASE    username
  #  SNAKE_CASE    user_name
  #  UPPER_CAMEL_CASE    UserName
  　jackson:
    　property-naming-strategy: LOWER_CAMEL_CASE
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
#      uri: mongodb://root:htData%402023*@36.138.30.68:27000,36.138.30.68:27001/?slaveOk=true&replicaSet=rs&readPreference=secondaryPreferred
#      uri: mongodb://root:htData%402023*@36.138.30.68:27000,36.138.30.68:27001
      uri: mongodb://root:htData%402023*@36.138.30.68:37017
#      host: 36.138.30.68
#      port: 37017
#      password: 'htData@2023*'
#      username: root
      database: poie_test
      authentication-database: admin
      auto-index-creation: false # 默认为false，即不会自动创建索引，
      transactionEnabled: true # 支持事务true
      option:
        max-connection-idle-time: 1500
        max-connection-per-host: 200
        max-wait-time: 60000
        max-connection-life-time: 0
        connect-timeout: 10000
        socket-timeout: 60000
  api-docs:
    enabled: true # 1. 是否开启 Swagger 接文档的元数据
    path: /v3/api-docs
  swagger-ui:
    enabled: true # 2.1 是否开启 Swagger 文档的官方 UI 界面
    path: /swagger-ui.html
  default-flat-param-object: true # 参见 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param 文档

knife4j:
  enable: true # 2.2 是否开启 Swagger 文档的 Knife4j UI 界面
  setting:
    language: zh_cn
  swagger-ui:
    path: doc.html

poie:
  info:
    version: 1.0.0
    base-package: com.icss.poie
  swagger:
    title: 管理后台
    description: 提供管理员管理的所有功能
    version: ${poie.info.version}
    base-package: ${poie.info.base-package}
