#dev环境  mysql7.0
v2:
  fileurl: D:/upload
  filetemp: D:/upload/temp

# mongodb 日志级别
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
spring:
  #  LOWER_CAMEL_CASE    userName    默认策略
  #  KEBAB_CASE    user-name
  #  LOWER_CASE    username
  #  SNAKE_CASE    user_name
  #  UPPER_CAMEL_CASE    UserName
  　jackson:
    　property-naming-strategy: LOWER_CAMEL_CASE
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb://root:htData%402023*@36.138.30.68:37017
#      host: 36.138.30.68
#      port: 37017
#      password: 'htData@2023*'
#      username: root
      database: poie_test
      authentication-database: admin
      auto-index-creation: false # 默认为false，即不会自动创建索引，
      transactionEnabled: false # 支持事务true
      option:
        max-connection-idle-time: 1500
        max-connection-per-host: 200
        max-wait-time: 60000
        max-connection-life-time: 0
        connect-timeout: 10000
        socket-timeout: 60000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite:.\sqllite\data.db
    url: jdbc:mysql://36.138.30.68:13306/poie_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: zrgj@2022*
    initial-size: 10
    max-active: 100
    min-idle: 30
    max-wait: 40
    validation-query: SELECT 1
    druid:
      # MySql、PostgreSQL、SqlServer、DaMeng校验
      validation-query: select 1
springdoc:
  api-docs:
    enabled: true # 1. 是否开启 Swagger 接文档的元数据
    path: /v3/api-docs
  swagger-ui:
    enabled: true # 2.1 是否开启 Swagger 文档的官方 UI 界面
    path: /swagger-ui.html
  default-flat-param-object: true # 参见 https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param 文档

knife4j:
  enable: true # 2.2 是否开启 Swagger 文档的 Knife4j UI 界面
  setting:
    language: zh_cn
  swagger-ui:
    path: doc.html

filling:
  info:
    version: 1.0.0
    base-package: com.filling.module.poi
  swagger:
    title: 管理后台
    description: 提供管理员管理的所有功能
    version: ${filling.info.version}
    base-package: ${filling.info.base-package}
